import Head from 'next/head'
import { useEffect } from 'react'
import { useDispatch , useSelector} from 'react-redux'
import { deleteClientAction, getClientAction, setClientAction } from '../state/Actions/clientAction'
import styles from '../styles/Home.module.scss'

export default function Home() {
  const client_info = useSelector(state=>state.client_info);
  const dispatch = useDispatch()
  useEffect(()=>{
    dispatch(getClientAction())
  },[])

  //status changing handler
  const stateHandler = (id,status)=>{
    console.log(status)
    if(status!=="next"){
      //update client status
      dispatch(setClientAction({id,status}))
    }else{
      //delete client
      console.log("delete")
      dispatch(deleteClientAction(id))
    }
    dispatch(getClientAction())
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Reservation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>
          Reservation
        </h1>
      </div>
      <main className='shadow p-3 mb-5 bg-body rounded'>
        {
          client_info.data?.map((item,index)=>(
            <div className="card" key={index}>
              <div className="card-body">
                <h5 className="card-title">{item.name}</h5>
                <h6 className="card-subtitle mb-2 text-muted">{item.info}</h6>
                <p className="card-text">{item.id}</p>
                <select name="progress" id="progress" className='form-select' onChange={(e)=>stateHandler(item.id,e.target.value)}>
                  <option value="arrive" selected={item.status==="arrive"}>Arrive</option>
                  <option value="consultation" selected={item.status==="consultation"}>Consultation</option>
                  <option value="finition" selected={item.status==="finition"}>Finition</option>
                  <option value="next">Next</option>
                </select>
              </div>
            </div>
          ))
        }
      </main>
    </div>
  )
}
