
//get client 
const GET_CLIENT_REQUEST = "GET_CLIENT_REQUEST"
const GET_CLIENT_SUCCESS = "GET_CLIENT_SUCCESS"
const GET_CLIENT_FAIL    = "GET_CLIENT_FAIL"

//set client
const SET_CLIENT_REQUEST = "SET_CLIENT_REQUEST"
const SET_CLIENT_SUCCESS = "SET_CLIENT_SUCCESS"
const SET_CLIENT_FAIL    = "SET_CLIENT_FAIL"

//remove client
const REMOVE_CLIENT_REQUEST = "REMOVE_CLIENT_REQUEST"
const REMOVE_CLIENT_SUCCESS = "REMOVE_CLIENT_SUCCESS"
const REMOVE_CLIENT_FAIL= "REMOVE_CLIENT_FAIL"


//add client 
const ADD_CLIENT_REQUEST = "ADD_CLIENT_REQUEST"
const ADD_CLIENT_SUCCESS = "ADD_CLIENT_SUCCESS"
const ADD_CLIENT_FAIL    = "ADD_CLIENT_FAIL"


export {
    GET_CLIENT_FAIL,GET_CLIENT_REQUEST,GET_CLIENT_SUCCESS,SET_CLIENT_FAIL,SET_CLIENT_REQUEST,SET_CLIENT_SUCCESS,REMOVE_CLIENT_FAIL,REMOVE_CLIENT_REQUEST,REMOVE_CLIENT_SUCCESS,
    ADD_CLIENT_FAIL,ADD_CLIENT_REQUEST,ADD_CLIENT_SUCCESS
}