import Head from 'next/head'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Reservation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>
          Reservation
        </h1>
      </div>
      <main className='shadow p-3 mb-5 bg-body rounded'>
        <div className="card">
          <div className="card-body">
            <h5 className="card-title">Client name</h5>
            <h6 className="card-subtitle mb-2 text-muted">Client info</h6>
            <p className="card-text">Client id</p>
            <select name="progress" id="progress" className='form-select'>
              <option value="arrive">Arrive</option>
              <option value="consultation">Consultation</option>
              <option value="finition">Finition</option>
              <option value="next">Next</option>
            </select>
          </div>
        </div>
        <div className="card" >
          <div className="card-body">
            <h5 className="card-title">Client name</h5>
            <h6 className="card-subtitle mb-2 text-muted">Client info</h6>
            <p className="card-text">Client id</p>
            <select name="progress" id="progress" className='form-select'>
              <option value="arrive">Arrive</option>
              <option value="consultation">Consultation</option>
              <option value="finition">Finition</option>
              <option value="next">Next</option>
            </select>
          </div>
        </div>
        <div className="card" >
          <div className="card-body">
            <h5 className="card-title">Client name</h5>
            <h6 className="card-subtitle mb-2 text-muted">Client info</h6>
            <p className="card-text">Client id</p>
            <select name="progress" id="progress" className='form-select'>
              <option value="arrive">Arrive</option>
              <option value="consultation">Consultation</option>
              <option value="finition">Finition</option>
              <option value="next">Next</option>
            </select>
          </div>
        </div>
        <div className="card" >
          <div className="card-body">
            <h5 className="card-title">Client name</h5>
            <h6 className="card-subtitle mb-2 text-muted">Client info</h6>
            <p className="card-text">Client id</p>
            <select name="progress" id="progress" className='form-select'>
              <option value="arrive">Arrive</option>
              <option value="consultation">Consultation</option>
              <option value="finition">Finition</option>
              <option value="next">Next</option>
            </select>
          </div>
        </div>
      </main>
    </div>
  )
}
